# Generated by Django 5.1.6 on 2025-03-05 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'ContactUs', 'verbose_name_plural': 'ContactUs'},
        ),
        migrations.AlterModelOptions(
            name='contactusform',
            options={'verbose_name': 'ContactUsForm', 'verbose_name_plural': 'ContactUsForm'},
        ),
    ]
