# Generated by Django 4.2.15 on 2024-10-19 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middlewares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_token', models.CharField(blank=True, max_length=500, null=True, verbose_name='User Token')),
                ('error_message', models.TextField(verbose_name='Error Message')),
                ('error_details', models.TextField(verbose_name='Error Details')),
                ('api_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Api Name')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
            ],
            options={
                'verbose_name': 'ErrorLog',
                'verbose_name_plural': 'ErrorLogs',
            },
        ),
    ]
