# Generated by Django 5.1.6 on 2025-03-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middlewares', '0002_errorlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_path', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('keywords', models.TextField()),
            ],
        ),
    ]
