# Generated by Django 5.1.6 on 2025-03-05 13:37

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content',
            field=django_quill.fields.QuillField(default='asd'),
            preserve_default=False,
        ),
    ]
