# Generated by Django 4.1 on 2025-03-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='slogan',
            field=models.CharField(default=2, max_length=50, verbose_name='Slogan'),
            preserve_default=False,
        ),
    ]
