# Generated by Django 4.1 on 2025-03-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_index_slogan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='index/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='index',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='index/logo/', verbose_name='Logo'),
        ),
    ]
