# Generated by Django 4.1 on 2025-03-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='profile',
            field=models.ImageField(default=1, upload_to='index/profile/', verbose_name='Profile'),
            preserve_default=False,
        ),
    ]
